#SkyLink GCS Settings
#Thu Sep 03 18:48:50 CST 2026
sampleInterval=1
phoneBaro=false
mapZoom=16
runMode=e1_real
phoneGps=true
baudRate=115200
phoneCompass=true
droneModel=DJI-M300
txRate=10
serialPort=COM3
theme=dark
e1Ip=192.168.4.1
heartbeatTimeout=3000
droneMaxRange=5000.0
e1Port=14550
